export const foodTypeList = [
  { label: 'Cơm', value: 'rice' },
  { label: 'Bún', value: 'noodle' },
  { label: 'Miến', value: 'vermicelli' },
  { label: 'Cháo', value: 'porridge' },
  { label: 'Phở', value: 'pho' },
  { label: 'Pizza', value: 'pizza' },
  { label: 'Trâu', value: 'buffalo' },
  { label: 'Dê', value: 'goat' },
  { label: 'Bò', value: 'beef' },
  { label: 'Gà', value: 'chicken' },
  { label: 'Trà sữa', value: 'milk_tea' },
  { label: 'Kem', value: 'ice_cream' },
  { label: 'Sữa chua', value: 'yogurt' },
  { label: 'Bánh Mỳ', value: 'bread' },
  { label: 'Cà phê', value: 'coffee' },
  { label: 'Sinh tố', value: 'smoothie' },
  { label: 'Nước Ép', value: 'juice' },
  { label: 'Soda', value: 'soda' },
];
